# Generated by KIMI AI

from typing import List, Tuple
from PIL import Image, ImageDraw


class MaxRectPacker():
    """
    Maximal Rectangles 二维装箱器。
    将不定大小矩形填入固定尺寸画布，直接修改 Char.pixPos 与 Char.pageID。
    """

    def __init__(self, canvas_size: Tuple[int, int]):
        self.bin_w, self.bin_h = canvas_size
        # 每个元素: (page_id, free_rects_list)
        # free_rects_list 元素: (x, y, w, h)
        self.bins: List[Tuple[int, List[Tuple[int, int, int, int]]]] = []

    # ------------------------------------------------------------------
    # 内部工具
    # ------------------------------------------------------------------
    @staticmethod
    def _intersect(r1: Tuple[int, int, int, int],
                   r2: Tuple[int, int, int, int]) -> bool:
        x1, y1, w1, h1 = r1
        x2, y2, w2, h2 = r2
        return (x1 < x2 + w2 and x1 + w1 > x2 and
                y1 < y2 + h2 and y1 + h1 > y2)

    def _split(self, free_rects: List[Tuple[int, int, int, int]],
               placed: Tuple[int, int, int, int]) -> List[Tuple[int, int, int, int]]:
        """放入矩形后，切割空闲矩形并剔除冗余"""
        px, py, pw, ph = placed
        new_rects: List[Tuple[int, int, int, int]] = []

        for fx, fy, fw, fh in free_rects:
            fr = (fx, fy, fw, fh)
            pr = (px, py, pw, ph)

            # 不相交 -> 直接保留
            if not self._intersect(fr, pr):
                new_rects.append(fr)
                continue

            # 相交 -> 切割成 4 个与放置矩形不相交的新块
            if px > fx:          # 左
                new_rects.append((fx, fy, px - fx, fh))
            if px + pw < fx + fw:  # 右
                new_rects.append((px + pw, fy, fx + fw - (px + pw), fh))
            if py > fy:          # 上
                new_rects.append((fx, fy, fw, py - fy))
            if py + ph < fy + fh:  # 下
                new_rects.append((fx, py + ph, fw, fy + fh - (py + ph)))

        # 冗余剔除：去掉被其他矩形完全包含的块
        result = []
        for i, r1 in enumerate(new_rects):
            x1, y1, w1, h1 = r1
            redundant = False
            for j, r2 in enumerate(new_rects):
                if i == j:
                    continue
                x2, y2, w2, h2 = r2
                if (x2 <= x1 and y2 <= y1 and
                        x2 + w2 >= x1 + w1 and y2 + h2 >= y1 + h1):
                    redundant = True
                    break
            if not redundant:
                result.append(r1)
        return result

    def _best_fit(self, free_rects: List[Tuple[int, int, int, int]],
                  w: int, h: int) -> Tuple[int, int, int] | None:
        """Best Area Fit：返回 (x, y, free_rect_index)，找不到返回 None"""
        best_idx = -1
        best_area = float('inf')
        best_pos = (0, 0)

        for i, (fx, fy, fw, fh) in enumerate(free_rects):
            if fw >= w and fh >= h:
                area = fw * fh
                if area < best_area:
                    best_area = area
                    best_idx = i
                    best_pos = (fx, fy)

        if best_idx == -1:
            return None
        return (*best_pos, best_idx)

    # ------------------------------------------------------------------
    # 公共接口
    # ------------------------------------------------------------------
    def pack(self, rects: List[Char]) -> None:
        """
        执行装箱。直接修改每个 R 的 pixPos 与 pageID。
        内部按面积从大到小排序处理。
        """
        sorted_rects = sorted(
            rects, key=lambda r: r.img.width * r.img.height, reverse=True)

        # 预检超界
        for rect in sorted_rects:
            rw, rh = rect.img.width, rect.img.height
            if rw > self.bin_w or rh > self.bin_h:
                raise ValueError(
                    f"矩形 {rw}x{rh} 超过画布尺寸 {self.bin_w}x{self.bin_h}"
                )

        for rect in sorted_rects:
            rw, rh = rect.img.width, rect.img.height
            placed = False

            # 1) 尝试已有画布
            for b_idx, (page_id, free_rects) in enumerate(self.bins):
                fit = self._best_fit(free_rects, rw, rh)
                if fit:
                    x, y, fr_idx = fit
                    rect.pixPos = (x, y)
                    rect.pageID = page_id

                    new_free = self._split(free_rects, (x, y, rw, rh))
                    self.bins[b_idx] = (page_id, new_free)
                    placed = True
                    break

            # 2) 需要新画布
            if not placed:
                new_page_id = len(self.bins)
                free_rects = [(0, 0, self.bin_w, self.bin_h)]
                fit = self._best_fit(free_rects, rw, rh)
                if fit is None:
                    raise RuntimeError(f"无法将矩形 {rw}x{rh} 放入新画布")

                x, y, _ = fit
                rect.pixPos = (x, y)
                rect.pageID = new_page_id

                new_free = self._split(free_rects, (x, y, rw, rh))
                self.bins.append((new_page_id, new_free))

    def page_count(self) -> int:
        """返回使用的画布数量"""
        return len(self.bins)

    def utilization(self, rects: List[Char]) -> float:
        """返回整体画布利用率 (0.0 ~ 1.0)"""
        used = sum(r.img.width * r.img.height for r in rects)
        total = self.page_count() * self.bin_w * self.bin_h
        return used / total if total else 0.0

    def visualize(self, rects: List[Char], save_path: str | None = None) -> Image.Image:
        """
        生成排版可视化图。每张画布横向拼接。
        若 save_path 提供则保存。
        """
        if not self.bins:
            return Image.new("RGBA", (1, 1), (0, 0, 0, 0))

        pages: dict[int, List[Char]] = {}
        for r in rects:
            pages.setdefault(r.pageID, []).append(r)

        page_imgs = []
        colors = [
            (255, 100, 100), (100, 255, 100), (100, 100, 255),
            (255, 255, 100), (255, 100, 255), (100, 255, 255),
            (200, 150, 50), (150, 50, 200),
        ]

        for pid in sorted(pages.keys()):
            img = Image.new("RGBA", (self.bin_w, self.bin_h),
                            (40, 40, 40, 255))
            draw = ImageDraw.Draw(img)
            for idx, r in enumerate(pages[pid]):
                x, y = r.pixPos
                w, h = r.img.width, r.img.height
                color = colors[idx % len(colors)]
                draw.rectangle(
                    [x, y, x + w - 1, y + h - 1],
                    fill=(*color, 220), outline=(255, 255, 255)
                )
                draw.text((x + 2, y + 2), str(idx), fill=(255, 255, 255))
            page_imgs.append(img)

        total_w = sum(im.width for im in page_imgs)
        max_h = max(im.height for im in page_imgs)
        result = Image.new("RGBA", (total_w, max_h), (20, 20, 20, 255))
        x_off = 0
        for im in page_imgs:
            result.paste(im, (x_off, 0))
            x_off += im.width

        if save_path:
            result.save(save_path)
        return result
